### ISSUE TITLE
Filter events using dates and times

### ISSUE THREAD

**Issue by lassijjk** [lassijjk/TurnUp#61]
EDIT 2 weeks after opening Issue:

This is mainly frontend feature utilising the proxy API we have now in place. But idea is to have some filter selectors such as date range, distance from user and selected tags. 

First two should be possible with the API endpoints we now have at place, but tags might require an additional table or two. 

Also one thing to keep in mind is if the frontpage gets too cluttered, we might have to hide these behind a dropdown or modal so that user can press a button to see filter options instead of showing them all at once.

**Comment by AnisulMahmud** [comment]
Is this backend work?

**Comment by lassijjk** [comment]
Well we need a nice looking frontend selectors for dates, maybe there is a nice material ui component for this? Then there is the choice of either filtering through the cards in frontend or doing another query. Filtering in frontend is probably doable now or just adding the selectors in frontend.

Lähetetty sovelluksesta Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Lähettäjä: Anisul Mahmud ***@***.***>
Lähetetty: Monday, October 9, 2023 5:17:46 PM
Vastaanottaja: lassijjk/TurnUp ***@***.***>
Kopio: Lassi Kirvesmäki ***@***.***>; Author ***@***.***>
Aihe: Re: [lassijjk/TurnUp] Filter events using dates and times (Issue #61)


Is this backend work?
